//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCampus.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartCampus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a dia_semana;hora;qtd
        ///3;1;4
        ///3;2;0
        ///3;3;0
        ///3;4;1
        ///3;5;0
        ///3;6;6
        ///3;7;5
        ///3;8;13
        ///3;9;24
        ///3;10;19
        ///3;11;19
        ///3;12;18
        ///3;13;14
        ///3;14;30
        ///3;15;18
        ///3;16;10
        ///3;17;15
        ///3;18;8
        ///3;19;9
        ///3;20;5
        ///3;21;2
        ///3;22;1
        ///3;23;0
        ///4;1;0
        ///4;2;0
        ///4;3;1
        ///4;4;0
        ///4;5;1
        ///4;6;0
        ///4;7;3
        ///4;8;16
        ///4;9;11
        ///4;10;7
        ///4;11;3
        ///4;12;1
        ///4;13;10
        ///4;14;14
        ///4;15;24
        ///4;16;19
        ///4;17;17
        ///4;18;21
        ///4;19;16
        ///4;20;9
        ///4;21;2
        ///4;22;2
        ///4;23;0
        ///5;1;0
        ///5;2;0
        ///5;3;0
        ///5;4;0
        ///5;5;0
        ///5;6;30
        ///5;7;79
        ///5;8;182
        ///5;9;216
        ///5;10;217
        ///5;11;195
        ///5;12;93
        ///5;13;127
        ///5;14;160
        ///5;15 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
    }
}
